[package]
name = "rstreamz"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rstreamz"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"

[profile.release]
lto = "thin"
